Added OAuth stuff and copyright info.

diff --git a/qataki b/qataki
--- a/qataki
+++ b/qataki
@@ -1,9 +1,12 @@
 #!/usr/bin/env bash
 
-#exit 99
-
 # Qataki is free and unencumbered public domain software. For more
 # information see http://unlicense.org/ or the accompanying UNLICENSE file.
+
+# The OAuth bits in this script (mainly TO_* functions and the accompanying
+# OAuth file) are copyright (c) 2010 by Yu-Jie Lin:
+# http://blog.yjl.im/2010/05/bash-oauth.html
+# The copyright statement can be found in the 'OAuth' file.
 
 # You can modify default options in $conf_file ($HOME/.qataki/qataki.conf)
 
@@ -714,21 +717,72 @@ fn_oauth_params() {
 	done
 }
 
+TO_extract_value() {
+	# $1 key name
+	# $2 string to find
+	egrep -o "$1=[a-zA-Z0-9-]*" <<< "$2" | cut -d\= -f 2
+}
+
+TO_access_token_helper() {
+	# Help guide user to get access token
+	local resp PIN
+	# Request Token
+	local auth_header="$(_OAuth_authorization_header 'Authorization' 'http://api.twitter.com/' "$oauth_consumer_key" "$oauth_consumer_secret" '' '' "$oauth_signature_method" "$oauth_version" "$(OAuth_nonce)" "$(OAuth_timestamp)" 'POST' "$T_REQUEST_TOKEN" "$(OAuth_param 'oauth_callback' 'oob')"), $(OAuth_param_quote 'oauth_callback' 'oob')"
+	resp=$(curl -k -s -d '' -H "$auth_header" "$T_REQUEST_TOKEN")
+	TO_rval=$?
+	[[ $? != 0 ]] && return $TO_rval
+	local _oauth_token=$(TO_extract_value 'oauth_token' "$resp")
+	local _oauth_token_secret=$(TO_extract_value 'oauth_token_secret' "$resp")
+
+	echo "Please go to the following link to get the PIN :"
+	echo "  ${T_AUTHORIZE_TOKEN}?$_oauth_token"
+
+	read -p 'PIN: ' PIN
+
+	# Access Token
+	local auth_header="$(_OAuth_authorization_header 'Authorization' 'http://api.twitter.com/' "$oauth_consumer_key" "$oauth_consumer_secret" "$_oauth_token" "$_oauth_token_secret" "$oauth_signature_method" "$oauth_version" "$(OAuth_nonce)" "$(OAuth_timestamp)" 'POST' "$T_ACCESS_TOKEN" "$(OAuth_param 'oauth_verifier' "$PIN")"), $(OAuth_param_quote 'oauth_verifier' "$PIN")"
+
+	resp=$(curl -k -s -d "" -H "$auth_header" "$T_ACCESS_TOKEN")
+	TO_rval=$?
+	[[ $? != 0 ]] && return $TO_rval
+
+	TO_ret=(
+		$(TO_extract_value 'oauth_token' "$resp")
+		$(TO_extract_value 'oauth_token_secret' "$resp")
+		$(TO_extract_value 'user_id' "$resp")
+		$(TO_extract_value 'screen_name' "$resp")
+		)
+}
+
 if [[ $site = *twitter* ]] ; then
-	auth=oauth
-	oauth_consumer_key=fOirkKnWy8eXni5RQBjG0A
-	oauth_consumer_secret=NrXPEk3APbCI0KetWzvKPjYPSqwjUycGBEL46WI
-	oauth_token='88505301-symeINu6Ls9RIYevgdBHMVFpNFG1lWXep2KZ6xErc'
-	oauth_token_secret='J5SmGZV4hCL1OLecqiQzdTjzoJ43Y4Lg72puBMVB2c'
-	source $HOME/.qataki/OAuth.sh
-	oauth_version='1.0'
+	auth=oauth ; oauth_version='1.0'
+	oauth_ck=5HU3imtp ; oauth_cs=hQYeyKLczJKazQ9zAgl0Erow
 	oauth_signature_method='HMAC-SHA1'
+	oauth_consumer_key=${oauth_ck}VId9R3YlrDVPSA
+	oauth_consumer_secret=${oauth_cs}zEl2DLDxE6jz3PYog
+	source $HOME/.qataki/OAuth.sh
+	oauth_token=$(grep ^oauth_token_twitter $conf_file)
+	oauth_token_secret=$(grep ^oauth_token_secret_twitter $conf_file)
+	eval oauth_token=${oauth_token#*=}
+	eval oauth_token_secret=${oauth_token_secret#*=}
+	if [[ -z $oauth_token || -z $oauth_token_secret ]] ; then
+		T_REQUEST_TOKEN='https://api.twitter.com/oauth/request_token'
+		T_AUTHORIZE_TOKEN='http://chr.tx0.org/qataki/oauth'
+		T_ACCESS_TOKEN='https://api.twitter.com/oauth/access_token'
+		TO_access_token_helper
+		if (( $? == 0 )); then
+			oauth_token=${TO_ret[0]}
+			oauth_token_secret=${TO_ret[1]}
+			echo "oauth_token_twitter='${TO_ret[0]}'" >> $conf_file
+			echo "oauth_token_secret_twitter='${TO_ret[1]}'" >> $conf_file
+		else
+			echo 'Unable to get access token'
+			exit 1
+		fi
+	fi
+
 	oauth_basic_params=$(fn_oauth_params 'oauth_consumer_key' "$oauth_consumer_key" \
 	  'oauth_signature_method' '$oauth_signature_method' 'oauth_version' '$oauth_version')
-	#source $HOME/.tcli.rc
-	#source $HOME/tests/tcli/TwitterOAuth.sh
-
-	#TO_init
 
 fi
 
